### ISSUE TITLE
你好，vscode开发，自定义的组件没有类型提示，始终显示any

### ISSUE THREAD

**Issue by euwei7** [uni-helper/create-uni#16]
### 描述问题

我使用vscode开发，在components里建立自定义组件，组件没有类型提示，鼠标移到组件名上显示any，导致在组件上设置props时，没有提示。

### 复现

page/index.js，鼠标移动到Footer组件名上
<img width="449" alt="image" src="https://github.com/uni-helper/create-uni/assets/120472761/ebe327cd-c535-4403-889b-e6a3f65a3e53">

### 系统信息

```Shell
mac
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by FliPPeDround** [comment]
感谢反馈，这是因为`<Footer />`组件引入使用了vite的别名
`import Footer from '@/components/Footer.vue'`
导致vscode无法定位到文件目录
最新版已经修改
你也可以将`jsconfig.json`文件，修改成下面
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "types": [
      "@dcloudio/types",
      "miniprogram-api-typings",
      "mini-types"
    ]
  },
}
```
![image](https://github.com/uni-helper/create-uni/assets/70848683/bb873acb-c350-4b54-be34-39ef2d02b412)
