### ISSUE TITLE
建议接入 uni-ui 组件库

### ISSUE THREAD

**Issue by Otto-J** [uni-helper/create-uni#20]
### 对问题的清晰和简明的描述

建议在初始化阶段补充接入 uni-ui 组件库，其他组件库一般都会明确知道如何接入 vite，uni-app 应该有自己的考虑没有明确指出，接入官方组件库应该可以帮助到更多使用 vite 方案的用户

### 推荐的解决方案

补充是否接入 uni-ui 组件库？

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by FliPPeDround** [comment]
@Otto-J 最新版本已经加上了组件库支持🎉🎉🎉
