### ISSUE TITLE
npx create-uni --info 调整 option

### ISSUE THREAD

**Issue by ModyQyW** [uni-helper/create-uni#36]
### 对问题的清晰和简明的描述

目前，`npx create-uni --info` 需要手动勾选需要输出的信息，这在报问题时并非那么方便。期望能调整 option，允许在执行命令前就指定勾选所有选项。

### 推荐的解决方案

`npx create-uni --info` 保留不变，增加 `npx create-uni --all-info` 表示勾选所有选项不再需要手动勾选。

### 额外上下文

https://github.com/uni-helper/.github/pull/4

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by FliPPeDround** [comment]
在v1.3.3版本中实现输出所有已安装uni-helper相关依赖
`npx create-uni --info all`

**Comment by ModyQyW** [comment]
我的理解是这样的：我们不知道用户是不是真的要反馈 uni-use 问题，也有可能是牵涉到别的地方，但是用户本身理解不太准确导致误报，如果我们不知道所有信息我们就不知道什么信息我们不需要（有点拗口但大概是这个意思）

**Comment by FliPPeDround** [comment]
> 我的理解是这样的：我们不知道用户是不是真的要反馈 uni-use 问题，也有可能是牵涉到别的地方，但是用户本身理解不太准确导致误报，如果我们不知道所有信息我们就不知道什么信息我们不需要（有点拗口但大概是这个意思），有点ptsd，但在某些情况下挺有用

好呢，已经实现了;)

**Comment by ModyQyW** [comment]
♥️太感谢你了
