### ISSUE TITLE
创建自定义模板项目 选择 nutui-uniapp 小程序无法编译通过

### ISSUE THREAD

**Issue by zhuchentong** [uni-helper/create-uni#45]
### 描述问题

创建自定义模板项目 选择 nutui-uniapp 小程序无法编译通过

`
npm run dev:mp-weixin
`

![image](https://github.com/uni-helper/create-uni/assets/4535888/20af3c81-4210-43aa-9b2b-5485e246d80c)

### 复现

`
npm create uni

// ui 选择 nutui-uniapp

npm run dev:mp-weixin
`

![image](https://github.com/uni-helper/create-uni/assets/4535888/d8bcac11-2123-4437-875d-67b13ebe601e)

### 系统信息

node: v20.11.0

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by FliPPeDround** [comment]
感谢反馈，因为uni最近版本导致小程序dev模式下手动导入组件会无法编译
https://github.com/dcloudio/uni-app/issues/4952

create-uni的uni已经回退到之前版本https://github.com/uni-helper/create-uni/commit/47bd2a94af4ae6b4073324a60ec3c65a7078e99a
