### ISSUE TITLE
使用 pnpm dev 时，重复创建相同项目名称会报错

### ISSUE THREAD

**Issue by Qtt9952** [uni-helper/create-uni#58]
### 描述问题

![image](https://github.com/user-attachments/assets/78ecd4ea-042f-475d-bc08-707b8e0a2b55)

### 复现

```sh
pnpm i
pnpm dev
npm link

create-uni hh
create-uni hh
```

### 系统信息

create-uni@1.5.0

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by FliPPeDround** [comment]
你好，感谢你的反馈
但我本地未能成功复现
![image](https://github.com/user-attachments/assets/45f88128-141b-4ef0-9532-b4e81bdf0634)

看起来你的使用方式是将仓库拉取到本地后npm link后执行create-uni命令，虽然不太清楚你这样做的目的
但我自己本地调试时，通常直接使用node命令`node create-uni/dist/outfile.cjs`

**Comment by Qtt9952** [comment]
感谢你的回复，我是先执行了 pnpm dev 的，操作流程如下：

![image](https://github.com/user-attachments/assets/c20129f9-a55a-4309-a41b-8c5bb9af77a4)

**Comment by FliPPeDround** [comment]
我换了windows也没能复现

![image](https://github.com/user-attachments/assets/d3714281-3422-4e54-8fa5-0531fc951d27)

可能需要再提供一些其他信息进行排查问题，比如错误的详情和node版本（仅支持18.x以上）
从报错信息来看是未能成功将原文件目录删除，此逻辑的代码在`index.ts`文件下114行
```ts
function emptyDir(dir: string) {
  if (!existsSync(dir))
    return

  postOrderDirectoryTraverse(
    dir,
    dir => rmdirSync(dir),
    file => unlinkSync(file),
  )
}

if (existsSync(root) && result.shouldOverwrite)
  emptyDir(root)
```

可以自行添加打印信息排查错误原因，

**Comment by FliPPeDround** [comment]
由于我无法复现，暂时先关闭了
