### ISSUE TITLE
建议引入uv-ui组件库

### ISSUE THREAD

**Issue by xushulang** [uni-helper/create-uni#59]
### 对问题的清晰和简明的描述

uv-ui是一个非常不错的组件库https://github.com/climblee/uv-ui

### 推荐的解决方案

https://github.com/climblee/uv-ui

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by FliPPeDround** [comment]
感谢你的反馈
目前`uv-ui`并没有提供支持[vite-plugin-uni-components](https://github.com/uni-helper/vite-plugin-uni-components)的自动引入，
使用uni的`easycom`自动引入，在volar下不能提供友好的类型支持

目前来说如果要支持`uv-ui`
需要先实现`vite-plugin-uni-components`的resolver，再使用`create-uni`引入
当然这不是阻碍，只是需要一点点时间
如果你有兴趣，期待你的pr

**Comment by FliPPeDround** [comment]
已在https://github.com/uni-helper/create-uni/commit/26e07909800459caf65312a0eecdf3ce56a6ab3e 支持

可以使用最新1.5.1版本查看
![image](https://github.com/user-attachments/assets/a1e5e6dc-e4ed-41d3-8f3f-91817a56d1e3)
