### ISSUE TITLE
[询问] 请问是否能加入 `@uni-ku/root` 至 插件列表？

### ISSUE THREAD

**Issue by Skiyee** [uni-helper/create-uni#60]
### 对问题的清晰和简明的描述

@uni-ku/root: https://github.com/uni-ku/root

目前能够支持 cli 和 hbx 创建的项目，基础功能已健全

该插件与 layouts 功能上可能会有点重叠，询问大佬是否能够加入

### 推荐的解决方案

@uni-ku/root 添加入到插件列表

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by FliPPeDround** [comment]
当然可以，非常欢迎
期待你的PR

只是有一个小小的疑问`**.ku.vue`, `ku`在这里的设计是出于什么考虑？
`**.root.vue`或者`**.global.vue`从语意上，个人觉得更清晰一些

**Comment by FliPPeDround** [comment]
> > 当然可以，非常欢迎 期待你的PR
> > 只是有一个小小的疑问`**.ku.vue`, `ku`在这里的设计是出于什么考虑？ `**.root.vue`或者`**.global.vue`从语意上，个人觉得更清晰一些
> 
> 感谢！❤
> 
> root.vue 是更好的选择，编写时没考虑那么多，变得一发不可收拾 😥

要是你认为有必要，在还没有推广，并没有多少用户的时候，是最适合修改的时候
随便一提，[uni-ku/root](https://github.com/uni-ku/root)这个名字并不符合vite插件的[社区命名规范](https://vitejs.cn/vite3-cn/guide/api-plugin.html#conventions)虽然不是很重要，但一个能让用户一眼就看出功能的命名，听起来会更合适。
要是你认为有必要修改的话，可以趁还没有推广前改改。当然保持原样同样也同样欢迎你的pr ；）

**Comment by Skiyee** [comment]
> 要是你认为有必要，在还没有推广，并没有多少用户的时候，是最适合修改的时候 随便一提，[uni-ku/root](https://github.com/uni-ku/root)这个名字并不符合vite插件的[社区命名规范](https://vitejs.cn/vite3-cn/guide/api-plugin.html#conventions)虽然不是很重要，但一个能让用户一眼就看出功能的命名，听起来会更合适。 要是你认为有必要修改的话，可以趁还没有推广前改改。当然保持原样，同样也欢迎你的pr ；）

在下一版本进行关于 App.ku.vue 命名更改的破坏性更新后，再提交相关的PR

包的命名可以会保持，我理解是这样的，uni 作为前缀就指定这是一个uniapp相关的包，鉴于部分使用者并不清楚vite插件命名规范，直接明了的命名，可能会使其更加容易理解 ❤

**Comment by FliPPeDround** [comment]
好呢，;) 
对了，大佬 有没有测试，App.ku.vue这样的文件命名方式会不会和[vite-plugin-uni-platform](https://github.com/uni-helper/vite-plugin-uni-platform)冲突

**Comment by Skiyee** [comment]
> 好呢，;) 对了，大佬 有没有测试，App.ku.vue这样的文件命名方式会不会和[vite-plugin-uni-platform](https://github.com/uni-helper/vite-plugin-uni-platform)冲突

应该不会，uni-platform库 是取 uni-env库 当前所在的 platform 作为识别扫描的

提交PR前我测试一下确保不产生冲突

**Comment by Skiyee** [comment]
由于时间关系，暂时先把该issue关闭推迟 ❤

**Comment by FliPPeDround** [comment]
> 由于时间关系，暂时先把该issue关闭推迟 ❤

没事，不急，挂着吧
