### ISSUE TITLE
用create-uni初始化项目的问题

### ISSUE THREAD

**Issue by XavierXuV5** [uni-helper/create-uni#69]
### 描述问题

1. 插件列表全部选中。
2. 模块列表全部选中。
3. UI组件选择[wot-design-uni](https://wot-design-uni.pages.dev/)
4. 包管理pnpm
5. Windows 10 22H2  node@20.12.2
分别在微信小程序和h5下的显示问题，均没有改动过任何配置。
![image](https://github.com/user-attachments/assets/e5993fa8-a91a-45ad-88df-b21dfdc6ac2d)
![image](https://github.com/user-attachments/assets/bb570de6-d6cc-4cfe-8468-8d97d126745d)

### 复现

均为项目初始化代码

### 系统信息

基础环境信息:
  - os: `Windows 10 10.0.19045`
  - node: `20.12.2`
  - packageManager: `pnpm`

基础依赖信息:
  - vue: `3.4.21`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-4020920240930001`

uni-helper依赖信息:
  - @uni-helper/vite-plugin-uni-platform: `0.0.4`

----------------------------------------------

🎯 感谢使用uni-helper，请提供虚线内的信息以便我们排查问题
   若还需提供其他信息，请自行修改补充

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by FliPPeDround** [comment]
感谢反馈，
在生成`vite.config.ts`文件时，插件顺序错误，导致自动引入组件样式丢失

暂时修改方案
```ts
import { fileURLToPath, URL } from 'node:url'

import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'
import Components from '@uni-helper/vite-plugin-uni-components'
import { WotResolver } from '@uni-helper/vite-plugin-uni-components/resolvers'

export default defineConfig({
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  },
  plugins: [
    Components({
      dts: true,
      resolvers: [WotResolver()]
    }),
	// 保证uni在Components下面
    uni(),
  ],
})
```

会在下个版本修复此问题

**Comment by FliPPeDround** [comment]
7b333020d8f0c4652104ef3508e8d252a6de8ed4 已修复

**Comment by XavierXuV5** [comment]
好的，非常感谢，项目组的开发人员。

**Comment by XavierXuV5** [comment]
项目组已修复，有同样问题的同学，pnpm create uni@1.6.0 升级一下
